name: Kubernetes deploy

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: deploy
      run: kubectl apply -f kompose
    - name: start grafana
      run: sudo ./grafana-starter.sh
    - name: expose address
      run: minikube ip
